[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Trading Journal Backend"
authors = ["suyash112006 <suyashzope789@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.13,<3.14"
flask = "^3.0.0"
flask-cors = "^4.0.0"
python-dotenv = "^1.0.1"
gunicorn = "^22.0.0"
sqlalchemy = "^2.0.46"
flask-sqlalchemy = "^3.1.1"
flask-login = "^0.6.3"
flask-mail = "^0.10.0"
pytz = "^2025.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
